name: Build and Lint check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read node and npm versions from package.json
      uses: skjnldsv/read-package-engines-version-actions@v1
      with:
        fallbackNode: '14.17.3'
        fallbackNpm: '7.20.0'
      id: package-engines-versions    
    - run: npm ci
    - run: npm run build


  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Read node and npm versions from package.json
      uses: skjnldsv/read-package-engines-version-actions@v1
      with:
        fallbackNode: '14.17.3'
        fallbackNpm: '7.20.0'
      id: package-engines-versions    
    - run: npm ci
    - run: npm --prefix frontend install && npm --prefix server install
    - name: Lint
