name: Build for ToolJet

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
 
  unit-test: 

      runs-on: ubuntu-latest
      env:
          TOOLJET_HOST: ${{secrets.TOOLJET_HOST}}
          LOCKBOX_MASTER_KEY: ${{secrets.LOCKBOX_MASTER_KEY}}
          SECRET_KEY_BASE: ${{secrets.SECRET_KEY_BASE}}
          NODE_ENV: ${{secrets.NODE_ENV}}
          PG_HOST: 5432
          PG_PORT: ${{secrets.PG_PORT}}
          PG_USER: ${{secrets.PG_USER}}
          PG_PASS: ${{secrets.PG_PASS}}
          PG_DB: ${{secrets.PG_DB}}
      steps:
        - uses: actions/checkout@v2
        - uses: harmon758/postgresql-action@v1
          with:
            postgresql version: '13'
        - run: npm --prefix server ci
        - run: npm run --prefix server db:create
        - run: npm run --prefix server db:migrate
        - run: npm --prefix server run test

  e2e-test: 

      runs-on: ubuntu-latest
      # env:
      #     TOOLJET_HOST: '${{secrets.TOOLJET_HOST}}'
      #     LOCKBOX_MASTER_KEY: '${{secrets.LOCKBOX_MASTER_KEY}}'
      #     SECRET_KEY_BASE: '${{secrets.SECRET_KEY_BASE}}'
      #     NODE_ENV: '${{secrets.NODE_ENV}}'
      #     PG_HOST: '${{secrets.PG_HOST}}'
      #     PG_PORT: '${{secrets.PG_PORT}}'
      #     PG_USER: '${{secrets.PG_USER}}'
      #     PG_PASS: '${{secrets.PG_PASS}}'
      #     PG_DB: '${{secrets.PG_DB}}'
      
      steps:
      - uses: actions/checkout@v2
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
      - run: npm ci
      - run: npm --prefix server ci
      - run: npm run --prefix server db:create
      - run: npm run --prefix server db:migrate
      - run: npm run --prefix server test:e2e